### ISSUE TITLE
In Session Object: "Created" is not a DateTime

### ISSUE THREAD

**Issue by Craaftx** [Zoapp/zoauth#5]
We have a `Session` Object which contains `created` attribute :
```
created: {
   type: "#DateTime",
},
```
But when we call it we got this :
```
created: 1519650493353
```

The `last` attribute of `Session` Object is the same and work great.

**Comment by Craaftx** [comment]
1519650493353 is an Unix time value but Only Mysql return this type. 

So we can't make some mathematical operation on it because it's not a DateTime Type.

**Comment by willdurand** [comment]
So the issue is caused by the mysql configuration we use here: https://github.com/Zoapp/core/blob/3c495b5a01965e749a846921a9fd8f8880268604/src/database/mysql/mysqlDatabase.js#L39 (zoapp-core). It is not cool to have such a configuration here because it makes difficult to understand why in-memory and mysql drivers behave differently.

It seems we can add some more configuration to return configured `Date` objects though: https://github.com/sidorares/node-mysql2/issues/262#issuecomment-285505131. I guess we should do that if we stick to this way of dealing with "UTC".

ping @mikbry because this seems important. What do you think?

**Comment by mikbry** [comment]
I thought i solved this issue with Date object. See line39 of MySQLDatabase:
      `dateStrings: true, // To fix mysql2 UTC mess see : https://github.com/sidorares/node-mysql2/issues/262`

**Comment by Craaftx** [comment]
Like @willdurand say to me we can use `new Date(timestamp)` to resolve this problem.

**Comment by mikbry** [comment]
ok if it fix and don't break previous instances
